name: Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run linters
        run: nps lint

      - name: Launch a postgres instance
        run: |
          docker run -d -p 5432:5432 -e POSTGRES_DB=db -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password postgres:13
          npx prisma migrate dev --schema ./prisma/schema.prisma
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/db

      - name: Launch a memcached instance
        run: docker run -d  -p 11211:11211 memcached:1.6.9

      - name: Run tests
        run: nps test
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/db

      - name: Publish test coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
